services:
  db:
    image: "grit42com/pgrdkit:16.3-2024.03.1"
    network_mode: "host"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-grit}
      - POSTGRES_DB=default
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-muchsecurepasswordwow}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    platform: linux/amd64
    restart: unless-stopped

volumes:
  postgres-data:
